# Generated by Django 6.0.1 on 2026-01-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
