# Generated by Django 5.2.8 on 2026-01-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookbeeapp", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(default="images/default.png", max_length=255),
        ),
    ]
