# Generated by Django 6.0.1 on 2026-01-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbeeapp', '0002_book_is_available_book_pincode'),
        ('bookbeeapp', '0005_order'),
    ]

    operations = [
    ]
