# Generated by Django 6.0.1 on 2026-01-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookbeeapp", "0005_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Fiction", "Fiction"),
                    ("Non-Fiction", "Non-Fiction"),
                    ("Sci-Fi", "Sci-Fi"),
                    ("Mystery", "Mystery"),
                    ("Romance", "Romance"),
                    ("Academic", "Academic"),
                    ("Fantasy", "Fantasy"),
                    ("Biography", "Biography"),
                    ("Self-Help", "Self-Help"),
                    ("Thriller", "Thriller"),
                    ("Other", "Other"),
                ],
                default="Fiction",
                max_length=50,
            ),
        ),
    ]
