# Generated by Django 6.0.1 on 2026-02-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookbeeapp", "0006_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="pincode",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
