# Generated by Django 6.0.1 on 2026-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookbeeapp", "0007_book_is_available_book_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(default="Unknown Author", max_length=200),
        ),
    ]
