# Generated by Django 6.0.1 on 2026-02-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookbeeapp", "0008_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Rent per 2 weeks or Sale price",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
